services:
  postgres:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: toyokawa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  grafana-lgtm:
    image: grafana/otel-lgtm:0.13.0
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart:
      unless-stopped

volumes:
  pgdata:
