ktor:
  application:
    modules:
      - com.toyokawa.ApplicationKt.module
  deployment:
    host: $HOST:127.0.0.1
    port: $PORT:8080
    watch:
      - classes
      - resources
  development: true
envConfig:
  env:
    $?KTOR_ENV
  database:
    user: $DB_USER
    password: $DB_PASSWORD
    url: $DB_URL
    className: $DB_DRIVER
